### ISSUE TITLE
always in actions page

### ISSUE THREAD

**Issue by lazymonkey2** [mbnuqw/wasm-detector#1]
Hi,
in firefox nightly 59 the icon os always in the page actions menu, and never in the address bar.
ex:
![immagine](https://user-images.githubusercontent.com/26486758/33514860-144702e0-d75b-11e7-9812-17e347a7b41d.png)

**Comment by mbnuqw** [comment]
Hi, sorry for long respond...
In ff 59 page actions always listed in that drop-down menu, even if pageAction is hidden.
Plus I initially wrote wrong title for inactive state, so here we are(...

I've updated these plugins, so hopes problem will disappear

**Comment by lazymonkey2** [comment]
I'll try it. Thanks!
