### ISSUE TITLE
Critical error, the addon blocks and breaks at least Mozilla page "submit new addon version"

### ISSUE THREAD

**Issue by serj-kzv** [mbnuqw/wasm-detector#5]
The addon blocks and breaks at least Mozilla page "submit new addon version". And I don't now what else the addon breaks. I have 'privacy.resistFingerprinting.block_mozAddonManager = true' to let addons work on Mozilla's pages.
I understand that It's just a error of the addon but I gave the one star to notify other users. I hope you will fix the error ASAP.

My system: 1) Firefox, last version. 2) Kubuntu 18.04 x64 3) I have tested that with the addon only.

UPD.
The addon blocks "upload" function of the Mozilla page.
I'll give the addon five stars if you fix the error. :)

**Comment by mbnuqw** [comment]
Fixed
Please, update extension
